omg it cant be true
mate-academy/react_static-list-of-posts pull request #1015
Opened 2022-07-07 12:08 UTC by Havrysh

2022-07-09 15:09 UTC, marina-tilniak requested changes
чому перший пост на вищому рівні?
<img width="603" alt="image" src="https://user-images.githubusercontent.com/94261494/178111489-d4bd3929-7197-487c-9766-d7fa2f788bc2.png">

2022-07-09 15:09 UTC, marina-tilniak commented on src/components/UserInfo/UserInfo.tsx
> +  </>
```suggestion
    </span>
  </>
```

2022-07-09 15:09 UTC, marina-tilniak commented on src/components/CommentList/CommentList.tsx
> +  comment: Comment[] | undefined;
```suggestion
  comments: Comment[] | undefined;
```

2022-07-09 15:09 UTC, marina-tilniak commented on src/components/CommentList/CommentList.tsx
> +          />
передавай сюди коментар і дестуктуризуй всередині. Якщо ти ці змінні більше нідк у цьому файлі не використовуєш, то немає сенсу витягувати їх тут з коментара

2022-07-09 15:09 UTC, marina-tilniak commented on src/components/PostList/PostList.tsx
> +          comment={comment}
те саме

2022-07-12 14:34 UTC, Bohdan-Maksymiuk approved these changes
GJ

2022-07-12 14:34 UTC, Bohdan-Maksymiuk commented on src/Variables/variables.ts
> +// console.log(preparedPosts);
😃

2022-07-12 14:34 UTC, Bohdan-Maksymiuk commented on src/components/CommentList/CommentList.tsx
> +  </>
```suggestion
    <ul>
      {comments
        && comments.map(comment => (
          <li key={comment.id}>
            <CommentInfo {...comment} />
          </li>
        ))}
    </ul>
```

2024-12-11 13:30 UTC, closed without merging