Solution
mate-academy/react_static-list-of-posts pull request #1083
Opened 2022-08-02 10:56 UTC by Kras4iy

[DEMO LINK](https://Kras4iy.github.io/react_static-list-of-posts/)

2022-08-02 19:10 UTC, LordAsmodey requested changes
Из документации реакта:
_Ключи помогают React определять, какие элементы были изменены, добавлены или удалены. Их необходимо указывать, чтобы React мог сопоставлять элементы массива с течением времени.
Лучший способ выбрать ключ — это использовать строку, которая будет явно отличать элемент списка от его соседей. Чаще всего вы будете использовать ID из ваших данных как ключи._

2022-08-02 19:10 UTC, LordAsmodey commented on src/components/PostList/PostList.tsx
> +    {posts.map(post => (
Когда в цикле вызываешь компонент, ему нужно передавать уникальный key
Checklist: point1

2022-08-02 19:10 UTC, LordAsmodey commented on src/components/CommentList/CommentList.tsx
> +          {comments.map(comment => <CommentInfo comment={comment} />)}
Тоже не хватает key

2022-08-03 08:02 UTC, VETALEK approved these changes
🔥

2022-08-03 08:02 UTC, VETALEK commented on src/components/CommentInfo/CommentInfo.tsx
> +      {' by '}
```suggestion
      by
```
you may use a plain text here

2022-08-03 08:02 UTC, VETALEK commented on src/components/UserInfo/UserInfo.tsx
> +  if (user instanceof Object) {
```suggestion
  if (user) {
```
more simple, but has the same effect 😉

2026-04-28 18:11 UTC, closed without merging