solution
mate-academy/react_static-list-of-posts pull request #1222
Opened 2022-10-03 20:15 UTC by ihorandrianov

[DEMO LINK](https://ihorandrianov.github.io/react_static-list-of-posts/)

2022-10-05 11:09 UTC, MaxManis approved these changes
Nice!)

2022-10-05 15:22 UTC, OleksiiBlezniuk requested changes

2022-10-05 15:22 UTC, OleksiiBlezniuk commented on src/components/PostList/PostList.tsx
> +    </div>
Let's use semantic tags for list and it's items
Also don't forget about `key` attribute (it should be in parent component, not in child)

2022-10-07 22:41 UTC, silchyn requested changes

2022-10-07 22:41 UTC, silchyn commented on src/components/CommentInfo/CommentInfo.tsx
> +  } = comment;
```suggestion
  const {
    name,
    email,
    body,
  } = comment;
```

2022-10-07 22:41 UTC, silchyn commented on src/components/PostInfo/PostInfo.tsx
> +  } = post;
```suggestion
  const {
    id,
    title,
    body,
    user,
    comments,
  } = post;
```

2022-10-07 22:41 UTC, silchyn commented on src/components/PostInfo/PostInfo.tsx
> +        )}
```suggestion
      <p className="PostInfo__body">
        {body}
      </p>
      
      {comments.length > 0
        ? <CommentList comments={comments} />
        : (
          <>
            <hr />
            <b data-cy="NoCommentsMessage">No comments yet</b>
          </>
        )}
```

2022-10-07 22:41 UTC, silchyn commented on src/components/PostList/PostList.tsx
> +    </div>
> Let's use semantic tags for list and it's items. Also don't forget about `key` attribute (it should be in parent component, not in child)

2022-10-07 22:41 UTC, silchyn commented on src/components/UserInfo/UserInfo.tsx
> +  } = user;
```suggestion
  const {
    name,
    username,
    email,
  } = user;
```

2022-10-12 14:13 UTC, naziamoff approved these changes
GJ

2022-10-12 14:13 UTC, naziamoff commented on src/components/CommentInfo/CommentInfo.tsx
> +        {' by '}
```suggestion
        <strong className="CommentInfo__name">
          {name}
        </strong>
        {' by '}
```

2022-10-12 14:13 UTC, naziamoff commented on src/components/PostInfo/PostInfo.tsx
> +      {comments.length > 0
We can keep it simple with boolean
```suggestion
      {comments.length
```

2023-10-31 12:07 UTC, closed without merging