solution
mate-academy/react_static-list-of-posts pull request #1473
Opened 2022-12-30 14:58 UTC by Kavster92

[DEMO LINK](https://Kavster92.github.io/react_static-list-of-posts/)

2023-01-03 09:59 UTC, nurdanokcu requested changes
Everything matches requirements. I added small suggestions . I will give it another look after the changes.

2023-01-03 09:59 UTC, nurdanokcu commented on src/components/CommentList/CommentList.tsx
> +    <div className="CommentList">
```suggestion
export const CommentList: React.FC<Props> = ({ comments }) => (
    <div className="CommentList">
```

It is only comments as props. So I believe this is shorter and more understandable.

2023-01-03 09:59 UTC, nurdanokcu commented on src/components/PostInfo/PostInfo.tsx
> +      {comments.length > 0 ? (
```suggestion
      {comments.length ? (
```

2023-01-04 08:41 UTC, meforoma approved these changes
✅

2023-01-04 08:47 UTC, meforoma approved these changes

2023-01-04 08:47 UTC, meforoma requested changes
test reject

2023-01-04 08:50 UTC, meforoma approved these changes

2023-01-25 13:28 UTC, closed without merging