Solution
mate-academy/react_static-list-of-posts pull request #1516
Opened 2023-01-24 20:27 UTC by offsset

https://offsset.github.io/react_static-list-of-posts/

2023-01-25 08:50 UTC, vlad-demchuk requested changes
fix linter issues (just push your types to repo)
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/102411130/214518546-389295da-4f2a-4cad-88fc-0e9df32f7997.png">
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/102411130/214518774-2442c3c1-dfa7-4891-850d-e21b89d30858.png">
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/102411130/214518970-4338ef81-e1fd-42a7-b150-09fd733649eb.png">

remove redundant react fragments

2023-01-25 08:50 UTC, vlad-demchuk commented on src/components/CommentInfo/CommentInfo.tsx
> +    <>
you don't need this fragment

2023-01-25 08:50 UTC, vlad-demchuk commented on src/components/CommentList/CommentList.tsx
> +  </>
```suggestion
    <div className="CommentList">
      <CommentInfo
        name={comments.name}
        email={comments.email}
        body={comments.body}
      />
    </div>
```

2023-01-25 08:50 UTC, vlad-demchuk commented on src/components/PostList/PostList.tsx
> +            comments={content.comments}
use destructuring

2023-01-25 19:59 UTC, TarasHoliuk requested changes

2023-01-25 19:59 UTC, TarasHoliuk commented on src/components/PostInfo/PostInfo.tsx
> +};
```suggestion
type Props = {
  post: {
    title: string;
    body: string;
    user: User | null;
    comments: Comments [];
  }
};
```

but better in this way:
```
type Props = {
  post: Post;
}
```

2023-01-25 19:59 UTC, TarasHoliuk commented on src/components/PostList/PostList.tsx
> +        <PostInfo {...content} />
don't pass props in this way
you should define one object in props and pass entire object

2023-01-25 19:59 UTC, TarasHoliuk commented on src/components/PostList/PostList.tsx
> +    { post.map(content => (
```suggestion
    {post.map(content => (
```

2023-01-25 19:59 UTC, TarasHoliuk commented on src/components/PostInfo/PostInfo.tsx
> +import { User } from '../../types/User';
you still didn't add it
type in terminal `git add .`, then commit and push
`git add .` will add newly created files

2023-02-08 18:50 UTC, TarasHoliuk approved these changes

2023-06-27 11:59 UTC, closed without merging