solution
mate-academy/react_static-list-of-posts pull request #1627
Opened 2023-03-13 11:30 UTC by Zelinskyi-Serhii

[DEMO LINK](https://Zelinskyi-Serhii.github.io/react_static-list-of-posts/)

2023-03-13 11:56 UTC, Anton-Tretiak approved these changes
Good Job!

2023-03-13 14:37 UTC, illiarerun requested changes

2023-03-13 14:37 UTC, illiarerun commented on src/components/PostInfo/PostInfo.tsx
> +        )}
```suggestion
      {comments.length === 0
        ? (<b data-cy="NoCommentsMessage">No comments yet</b>)
        : (<CommentList comments={comments} />)
      }
```

2023-03-13 14:37 UTC, illiarerun commented on src/components/PostList/PostList.tsx
> +      {posts.map((post) => <PostInfo post={post} key={post.id} />)}
Again, don't write code in one line

2023-03-13 14:37 UTC, illiarerun commented on src/components/PostInfo/PostInfo.tsx
> +          {user && <UserInfo user={user} key={user.id} />}
you don't need key here, you're not mapping users
```suggestion
          {user && <UserInfo user={user} />}
```

2023-03-20 19:34 UTC, sergii-nosachenko requested changes

2023-03-20 19:34 UTC, sergii-nosachenko commented on src/App.tsx
> +function getCommentsById(postId: number): Comments[] {
```suggestion
function getCommentsByPostId(postId: number): Comments[] {
```

2023-03-20 19:34 UTC, sergii-nosachenko commented on src/App.tsx
> +  const foundComments = commentsFromServer
Immediately return

2023-03-20 19:34 UTC, sergii-nosachenko commented on src/types/Comments.ts
> +export interface Comments {
```suggestion
export interface Comment {
```

2023-03-20 19:34 UTC, sergii-nosachenko commented on src/types/Posts.ts
> +export interface Posts {
```suggestion
export interface Post {
```

You describe one entity here

2023-03-20 19:34 UTC, sergii-nosachenko commented on src/types/Users.ts
> +export interface Users {
Same here

2023-03-20 19:34 UTC, sergii-nosachenko commented on src/components/CommentInfo/CommentInfo.tsx
> +        <strong className="CommentInfo__name">{name}</strong>
Split into rows

2023-03-20 19:34 UTC, sergii-nosachenko commented on src/components/CommentList/CommentList.tsx
> +  return (
Useless `return`

2023-03-20 19:34 UTC, sergii-nosachenko commented on src/components/PostInfo/PostInfo.tsx
> +        <h3 className="PostInfo__title">{title}</h3>
Split

2023-03-20 19:34 UTC, sergii-nosachenko commented on src/components/PostInfo/PostInfo.tsx
> +        <p>
Check if user exists here

2023-03-20 19:34 UTC, sergii-nosachenko commented on src/components/PostInfo/PostInfo.tsx
> +      {comments.length
Add space

2023-03-20 19:34 UTC, sergii-nosachenko commented on src/components/PostList/PostList.tsx
> +  return (
Useless

2023-03-22 08:08 UTC, sergii-nosachenko approved these changes
Good work 👍
Commented

2023-03-22 08:08 UTC, sergii-nosachenko commented on src/components/PostInfo/PostInfo.tsx
> +        {user && (
```suggestion

        {user && (
```

2023-03-22 08:08 UTC, sergii-nosachenko commented on src/components/PostInfo/PostInfo.tsx
> +          </p>
Paragraph is a part of UserInfo component

2023-07-12 19:47 UTC, closed without merging