first solution
mate-academy/react_static-list-of-posts pull request #258
Opened 2020-09-01 17:31 UTC by krajnova

[DEMO LINK](https://krajnova.github.io/react_static-list-of-posts/)

2020-09-01 17:42 UTC, nanccyy approved these changes
Nice!

2020-09-01 18:35 UTC, vsm2k17 requested changes

2020-09-01 18:35 UTC, vsm2k17 commented on src/Comment/Comment.js
> +  </>
давай тут добавим якусь обгортку замість React.Fragment, щоб comment був самодостатнім компонентом і не залежав від зовнішніх компонентів, так його можна буде перевикористати десь ще

2020-09-01 18:35 UTC, vsm2k17 commented on src/Post/Post.js
> +  </>
те саме, що і Comment

2020-09-01 18:35 UTC, vsm2k17 commented on src/User/User.js
> +  </>
Думай про те чи можна перевикористати твій компонент десь іще, цей компонент потребує вставки в якийсь тег, треба так писати компонент щоб при перенесенні його в інше місце в коді, він всерівно працював

2020-09-02 09:19 UTC, vsm2k17 approved these changes

2020-09-02 09:19 UTC, vsm2k17 commented on src/App.js
> +    <PostList preparedList={preparedList} />
```suggestion
    <PostList list={preparedList} />
```

2025-01-27 11:20 UTC, closed without merging