Solution
mate-academy/react_static-list-of-posts pull request #268
Opened 2020-09-02 12:03 UTC by Andrii256

https://andrii256.github.io/react_static-list-of-posts/

2020-09-02 12:33 UTC, furude-rika approved these changes
все круто!
написала небольшие замечания по стилю кода

2020-09-02 12:33 UTC, furude-rika commented on src/components/Post/Post.js
> +    <p className="Post__body">
почему ниже ставишь пустые строки между тегами, а между h2 и p нет?

2020-09-02 12:33 UTC, furude-rika commented on src/components/User/User.js
> +      Author
думаю, такой короткий контент нет смысла на новую строку переносить

2020-09-02 14:17 UTC, Andrii256 commented on src/components/Post/Post.js
> +    <p className="Post__body">
ну типу вони як брати, прям дуже близькі брати

2020-09-02 14:17 UTC, Andrii256 commented on src/components/User/User.js
> +      Author
ну впринципі да, далі не буду

2020-09-02 14:53 UTC, vsm2k17 requested changes

2020-09-02 14:53 UTC, vsm2k17 commented on src/components/Comment/Comment.js
> +  email: PropTypes.string,
я думаю пошта теж обов'язкова

2020-09-02 14:53 UTC, vsm2k17 commented on src/components/CommentList/CommentList.js
> +  comments: PropTypes.arrayOf(object),
```suggestion
  comments: PropTypes.arrayOf(PropTypes.object),
```

2020-09-02 14:53 UTC, vsm2k17 commented on src/components/Post/Post.js
> +  comments: PropTypes.arrayOf(object),
```suggestion
  comments: PropTypes.arrayOf(PropTypes.object),
```

2020-09-02 14:53 UTC, vsm2k17 commented on src/components/PostList/PostList.js
> +  posts: PropTypes.arrayOf(object).isRequired,
```suggestion
  posts: PropTypes.arrayOf(PropTypes.object).isRequired,
```

2020-09-02 14:53 UTC, vsm2k17 commented on src/components/PostList/PostList.js
> +  posts: PropTypes.arrayOf(object).isRequired,
Або 
```
posts: PropTypes.arrayOf(PropTypes.shape({
  id: PropTypes.number.isRequired,
})
).isRequired 
```

2020-09-02 14:53 UTC, vsm2k17 commented on src/components/User/User.js
> +  address: PropTypes.shape().isRequired,
ти використовуєш тут властивості address тому потрбіно їх описати в PropTypes.shape(.....)

2020-09-02 15:16 UTC, Andrii256 commented on src/components/User/User.js
> +  address: PropTypes.shape().isRequired,
Доречі. Уявімо, що поле suite не обов'язкове. Як прописати йому дефолтне значення?

2020-09-02 15:25 UTC, vsm2k17 commented on src/components/User/User.js
> +  address: PropTypes.shape().isRequired,
Заходиш туди це він приходить в пропсах і прописуєш

2020-09-02 15:26 UTC, vsm2k17 approved these changes

2021-03-09 23:30 UTC, closed without merging

2021-03-09 23:31 UTC, Andrii256 commented
We're good