added solutiom
mate-academy/react_static-list-of-posts pull request #356
Opened 2021-01-13 12:45 UTC by MarchD

[DEMO LINK](https://MarchD.github.io/react_static-list-of-posts/)

2021-01-13 15:37 UTC, troospieler approved these changes
good job

2021-01-15 11:27 UTC, aionova requested changes
Good start!

2021-01-15 11:27 UTC, aionova commented on src/components/Comment/Comment.js
> +Comment.propTypes = TypeOfComment.isRequired;
```suggestion
Comment.propTypes = {
  name: PropTypes.string.isRequired,
  body: PropTypes.string.isRequired,
  email: PropTypes.string.isRequired,
};
```
If you've destructured comment object and pass separate props, you need to describe their types separately.

2021-01-15 11:27 UTC, aionova commented on src/components/Post/Post.js
> +Post.propTypes = TypeOfPost.isRequired;
same here

2021-01-15 11:27 UTC, aionova commented on src/components/User/User.js
> +User.propTypes = TypeOfUser.isRequired;
```suggestion
User.propTypes = {
  user: TypeOfUser.isRequired,
}
```

2021-01-15 11:45 UTC, aionova approved these changes
Good job!

2021-01-15 11:45 UTC, aionova commented on src/components/CommentList/CommentList.js
> +CommentList.propTypes = TypeOfCommentsList.isRequired;
```suggestion
CommentList.propTypes = {
  comments: TypeOfCommentsList.isRequired,
};
```

2021-01-15 11:45 UTC, aionova commented on src/components/PostList/PostList.js
> +PostList.propTypes = TypeOfPostsList.isRequired;
```suggestion
PostList.propTypes = {
  posts: TypeOfPostsList.isRequired,
};
```

2021-01-15 11:46 UTC, MarchD commented on src/components/CommentList/CommentList.js
> +CommentList.propTypes = TypeOfCommentsList.isRequired;
😞

2024-01-07 21:30 UTC, closed without merging