Fs may19 olha
mate-academy/react_static-list-of-posts pull request #36
Opened 2019-07-03 08:19 UTC by OlgaLyubicheva

[Demo link](https://olgalyubicheva.github.io/react_static-list-of-posts/)

2019-07-03 14:54 UTC, ValeriiKupyna commented on src/App.js
> +        <PostList
виписок Post має рендеиртись в PostList а в даному випатку назва компоненти не відпоідає її функціональності

2019-07-03 14:54 UTC, ValeriiKupyna commented on src/App.js
> +        <PostList
відсутній key

2019-07-03 14:54 UTC, ValeriiKupyna commented on src/components/PostList/PostList.js
> +    />
тут має бути map по posts і в середині рендеритись Post який приймає дані про конкретний пост. 
і в середині рендерить commentsList і User

2019-07-03 14:54 UTC, ValeriiKupyna commented on src/components/PostList/PostList.js
> +  user: PropTypes.arrayOf(PropTypes.object).isRequired,
user це однина ожше або назва пропса не вірна або проптайпу

2019-07-03 14:54 UTC, ValeriiKupyna commented on src/components/PostList/PostList.js
> +  user: PropTypes.arrayOf(PropTypes.object).isRequired,
якщо використовує проп ттайп то опиши дані в масиві за допомогою shape

2019-07-03 14:54 UTC, ValeriiKupyna commented on src/components/User.js
> +const User = ({ name = null, username = null, email, address = null }) => (
тут дефолтні значення не потрібні вони будуть братись з defaultProps

2019-07-03 14:54 UTC, ValeriiKupyna commented on src/components/Comment.js
> +      <h4>{item.name || null}</h4>
для чого null? undefined теж не буде рендеретись

2019-07-03 14:54 UTC, ValeriiKupyna commented on src/components/Comment.js
> +const Comment = ({ item }) => (
item  не підходяща назва для пропса

2019-07-03 14:54 UTC, ValeriiKupyna commented on src/components/CommentList/CommentList.js
> +const CommentList = ({ comments = null }) => (
comments по дефолту буде братись з defaultProps

2019-07-03 14:54 UTC, ValeriiKupyna commented on src/components/Post.js
> +  comments: PropTypes.arrayOf(PropTypes.object),
опиши структуру comment

2019-07-03 14:54 UTC, ValeriiKupyna commented on src/components/PostList/PostList.js
> +      address={user.address}
чому неможна передати просто user

2019-07-03 14:54 UTC, ValeriiKupyna commented on src/components/PostList/PostList.js
> +      address={user.address}
чому неможна передати просто user

2019-07-03 14:54 UTC, ValeriiKupyna commented on src/components/User.js
> +    {address && `${address.city}, ${address.street} Street`}
address.city буде undefined то так і вивидеться undefined в стороці

2019-07-03 16:53 UTC, OlgaLyubicheva commented on src/components/PostList/PostList.js
> +  user: PropTypes.arrayOf(PropTypes.object).isRequired,
не зрозуміла де саме треба його використати. Для "user: PropTypes.arrayOf(PropTypes.object)" ? Тоді не розумію навіщо

2019-07-03 16:56 UTC, OlgaLyubicheva commented on src/components/Post.js
> +  comments: PropTypes.arrayOf(PropTypes.object),
це масив з об'єктів. Треба описати з яких саме?

2019-07-04 07:42 UTC, vpolets requested changes

2019-07-04 07:42 UTC, vpolets commented on src/components/Comment.js
> +const Comment = ({ oneComment }) => (
просто comment не треба префіксу one

2019-07-04 07:42 UTC, vpolets commented on src/components/Post/Post.js
> +      name={user.name}
передай в компонент просто user і там його вже розбирай

2019-07-04 07:42 UTC, vpolets commented on src/components/PostList.js
> +          key={`post${post.id}`}
аналогічно просто post передай можна передати ось так <Post {...post} /> а в пості прийняти потрібні поля

2019-07-04 07:42 UTC, vpolets commented on src/components/PostList.js
> +          key={`post${post.id}`}
Тим більше ти так і робиш, приймаєш потрібні поля тому тут передати ось так як я написав буде простіше

2019-07-04 08:49 UTC, OlgaLyubicheva commented on src/components/Comment.js
> +const Comment = ({ oneComment }) => (
мені здалося, що забагато змінних з однаковою назвою і все стає якось заплутано. Це принципово, ім'я аргумента, чи взагалі так не прийнято називати аргументи (враховуючи, що назва повинна відповідати суті)?

2019-07-04 09:03 UTC, OlgaLyubicheva commented on src/components/PostList.js
> +          key={`post${post.id}`}
А не має значення кількість аргументів які я передаю і кількість яку з них використовую?
Наприклад, якщо я передаю так {...arr} і в масиві було десь 15-ть елементів, то в мене буде 15-ть переданих аргументів, а використаю я тільки один? Тобто, це взагалі не має ні якого впливу на роботу коду? Чи є якісь загальні правила, як роботи не треба бо це зайве?

2019-07-04 16:00 UTC, volodymyrkryvytskyy commented on src/components/PostList.js
> +          key={`post${post.id}`}
Нет, в большинстве случаев это никак не влияет на работу кода. Работа с API обычно так и происходит. Ты делаешь запрос к серверу, получаешь объект с, к примеру, 50 ключами. И уже из этого объекта достаешь те ключи, которые нужны тебе для работы твоего приложения.
Так и тут, отправляешь один объект `post` и из него достаешь то, что тебе нужно для работы.

2019-07-04 16:06 UTC, vkryvytskyi approved these changes

2025-06-05 13:43 UTC, closed without merging