solution
mate-academy/react_static-list-of-posts pull request #514
Opened 2021-05-20 14:21 UTC by BilliZane

[DEMO LINK](https://BilliZane.github.io/react_static-list-of-posts/)

2021-05-20 14:49 UTC, taya294 approved these changes
Great! 
Looks good for me))

2021-05-20 15:24 UTC, VinnieJ-2k20 requested changes
Nice solution.
Need to fix couple of things.

2021-05-24 08:38 UTC, varseniuk approved these changes
Great job! 👍 
Left some comments

2021-05-24 08:38 UTC, varseniuk commented on src/api/components/Comment/Comment.js
> +    <a href={`mailto: ${email}`} className="Comment__email">
👍

2021-05-24 08:38 UTC, varseniuk commented on src/api/components/CommentList/CommentList.js
> +    PropTypes.shape({}),
It would be better to describe `comment.id` here, because you use it in this component

2021-05-24 08:38 UTC, varseniuk commented on src/api/components/PostList/PostList.js
> +    PropTypes.shape({}),
```suggestion
    PropTypes.shape({
      id: PropTypes.number.isRequired,
    }),
```
You use `id` here so it's better to describe it

2023-09-26 15:12 UTC, closed without merging