Task was solved
mate-academy/react_static-list-of-posts pull request #699
Opened 2021-11-05 12:32 UTC by cyb1ove

[DEMO LINK](https://cyb1ove.github.io/react_static-list-of-posts/)

2021-11-05 16:12 UTC, dima-narozhnyi approved these changes
Nicely done!

2021-11-08 17:43 UTC, solaryasha requested changes

2021-11-08 17:43 UTC, solaryasha commented on src/App.tsx
> +    ))}
Implement an application with 5 components PostList

2021-11-08 17:43 UTC, solaryasha commented on src/components/CommentList/CommentList.scss
> +  &__content:last-child {
Використовуй `&` для вкладених селекторів

2021-11-08 17:43 UTC, solaryasha commented on src/types/types.ts
> +  user: (User | null);
```suggestion
  user: User | null;
```

2021-11-08 17:43 UTC, solaryasha commented on src/components/PostInfo/PostInfo.tsx
> +    <CommentList comments={post.comments} />
Треба врахувати випадок, що масив `comments` може бути пустим

2021-11-08 17:43 UTC, solaryasha commented on src/components/UserPost/UserPost.tsx
> +};
Давай відокремимо PostInfo i UserInfo

2021-11-09 14:52 UTC, solaryasha approved these changes

2021-11-09 14:52 UTC, solaryasha commented on src/App.tsx
> +    <PostList preparedPosts={preparedPosts} />
```suggestion
    <PostList posts={preparedPosts} />
```

2025-01-20 16:32 UTC, closed without merging