Develop
mate-academy/react_static-list-of-posts pull request #784
Opened 2022-01-17 14:54 UTC by andrii-koptiev

https://andrii-koptiev.github.io/react_static-list-of-posts/

2022-01-17 15:27 UTC, Bohdan-Maksymiuk reviewed
🔥🔥🔥

2022-01-17 15:27 UTC, Bohdan-Maksymiuk commented on src/components/CommentList/CommentList.tsx
> +      {comments && (
Можливо тут перевірку краще зробити перед ul, щоб навіть він не рендерився при відсутності коментів

2022-01-17 15:27 UTC, Bohdan-Maksymiuk approved these changes

2022-01-18 10:46 UTC, Elena-brv requested changes

2022-01-18 10:46 UTC, Elena-brv commented on src/App.tsx
> +  comments: commentsFromServer.filter(c => c.postId === post.id) as Comment[],
```suggestion
  comments: commentsFromServer.filter(comment => comment.postId === post.id),
```

2022-01-18 10:46 UTC, Elena-brv commented on src/App.tsx
> +  user: usersFromServer.find(u => u.id === post.userId) || null,
do not shorten variable names

2022-01-18 10:46 UTC, Elena-brv commented on src/components/CommentList/CommentList.tsx
> +      {comments && (
do as @Bohdan-Maksymiuk has suggested,
and comments couldn't be false, it's empty or not empty array

2022-01-18 10:46 UTC, Elena-brv commented on src/components/CommentList/CommentList.tsx
> +  comments: Comment[] | null;
```suggestion
  comments: Comment[];
```

2022-01-18 10:46 UTC, Elena-brv commented on src/components/PostInfo/PostInfo.tsx
> +  post: Post
```suggestion
  post: Post,
```

2022-01-18 10:46 UTC, Elena-brv commented on src/components/UserInfo/UserInfo.tsx
> +      {user.name}
wrap into some html element

2022-01-18 18:22 UTC, andrii-koptiev commented on src/App.tsx
> +  user: usersFromServer.find(u => u.id === post.userId) || null,
Изменил, но на практике утренней Дима нам говорил, что можем так делать в таких случаях. Когда у нас нет особой логики и нужно что то найли или отфильтровать

2022-01-19 11:45 UTC, Elena-brv requested changes

2022-01-19 11:45 UTC, Elena-brv commented on src/components/CommentList/CommentList.tsx
> +    {commentaries && (
комментарии - это у тебя массив, пустой или нет - в любом случае он будет `true`, тут нужна другая проверка

2022-01-19 12:11 UTC, andrii-koptiev commented on src/components/CommentList/CommentList.tsx
> +    {commentaries && (
agree. done

2022-01-19 14:37 UTC, Elena-brv approved these changes

2023-09-26 21:11 UTC, closed without merging