Develop
mate-academy/react_static-list-of-posts pull request #790
Opened 2022-01-17 21:16 UTC by mykola-koval

[DEMO LINK](https://mykola-koval.github.io/react_static-list-of-posts/)

2022-01-18 08:40 UTC, vladyslav-harkusha approved these changes

2022-01-18 10:40 UTC, Elena-brv requested changes

2022-01-18 10:40 UTC, Elena-brv commented on src/components/CommentList/CommentList.tsx
> +    {comments.map(comment => <CommentInfo comment={comment} />)}
add key

2022-01-18 10:40 UTC, Elena-brv commented on src/components/PostList/PostList.tsx
> +        <CommentList comments={post.comments} />
CommentsList should be inside PostInfo

2022-01-19 10:55 UTC, Elena-brv approved these changes

2022-01-19 10:55 UTC, Elena-brv commented on src/components/CommentList.tsx
> +    {comments.map(comment => <CommentInfo key={comment.id} comment={comment} />)}
```suggestion
    {comments.map(comment => (
      <CommentInfo key={comment.id} comment={comment} />
    ))}
```

2022-01-19 10:55 UTC, Elena-brv commented on src/components/UserInfo.tsx
> +  <p className="has-text-right">{`posted by @${user.username} (${user.name}) <${user.email}>`}</p>
```suggestion
  <p className="has-text-right">
    {`posted by @${user.username} (${user.name}) <${user.email}>`}
  </p>
```

2023-03-02 07:59 UTC, closed without merging