implement components for post list
mate-academy/react_static-list-of-posts pull request #902
Opened 2022-05-02 18:07 UTC by misha200119

[DEMO LINK](https://misha200119.github.io/react_static-list-of-posts/)

2022-05-05 13:54 UTC, plankton9991 approved these changes
Great job)

2022-05-05 13:54 UTC, plankton9991 commented on src/interfaces/User.tsx
> +    bs: string;
Не впевнений що це протрібно

2022-05-05 14:38 UTC, MaksimusCRS requested changes

2022-05-05 14:38 UTC, MaksimusCRS commented on src/components/PostInfo/PostInfo.tsx
> +      <UserInfo user={post.user} />
Render it only if u have user

2022-05-06 08:52 UTC, MaksimusCRS requested changes

2022-05-06 08:52 UTC, MaksimusCRS commented on src/components/PostInfo/PostInfo.tsx
> +    (!post.user)
Cейчас ты рендеришь компонент, если у тебя нету юзера...

2022-05-06 10:59 UTC, MaksimusCRS approved these changes

2022-05-12 07:49 UTC, Andr1yK approved these changes

2025-08-10 12:55 UTC, closed without merging