add list of posts
mate-academy/react_static-list-of-posts pull request #917
Opened 2022-05-04 18:52 UTC by kkiirill

[DEMO LINK](https://kkiirill.github.io/react_static-list-of-posts/)

2022-05-04 19:11 UTC, StasivPavlo approved these changes
👍

2022-05-05 08:25 UTC, danylo-onishchuk requested changes

2022-05-05 08:25 UTC, danylo-onishchuk commented on src/Components/PostInfo/PostInfo.tsx
> +  console.log(post.comment);
???

2022-05-05 13:40 UTC, danylo-onishchuk approved these changes

2023-01-03 18:32 UTC, closed without merging