solution
mate-academy/react_static-list-of-posts pull request #947
Opened 2022-05-29 14:08 UTC by ZUBOV-ILLIA

[DEMO LINK](https://ZUBOV-ILLIA.github.io/react_static-list-of-posts/)

2022-05-29 15:21 UTC, vlad-demchuk approved these changes

2022-05-31 16:57 UTC, Anna-Tkachenko requested changes

2022-05-31 16:57 UTC, Anna-Tkachenko commented on src/App.tsx
> +const makingArray = (
```suggestion
const getPreparedPosts = (
```

2022-05-31 16:57 UTC, Anna-Tkachenko commented on src/components/CommentList/CommentList.tsx
> +      <CommentInfo comment={comment} />
Don't forget about key attribute

2022-05-31 16:57 UTC, Anna-Tkachenko commented on src/components/CommentList/CommentList.tsx
> +export const CommentList: React.FC<Props> = ({ post }) => (
CommentList component should accept only comments array instead of full post

2022-06-01 13:07 UTC, Anna-Tkachenko approved these changes

2025-03-11 09:24 UTC, closed without merging