solution
mate-academy/react_static-list-of-posts pull request #962
Opened 2022-05-31 19:12 UTC by yelnikov-andrii

[DEMO LINK](https://yelnikov-andrii.github.io/react_static-list-of-posts/)

2022-06-02 16:08 UTC, Anna-Tkachenko requested changes

2022-06-02 16:08 UTC, Anna-Tkachenko commented on src/components/CommentList/CommentList.tsx
> +        <CommentInfo {...com} />
CommentInfo component should accept full comment object
<CommentInfo comment={...} />

2022-06-02 16:08 UTC, Anna-Tkachenko commented on src/components/PostList/PostList.tsx
> +        <UserInfo {...prep} />
Same here
Pass full post and full user object on some field in props object

2022-06-02 16:08 UTC, Anna-Tkachenko commented on src/components/PostList/PostList.tsx
> +        <UserInfo {...prep} />
And don't render UserInfo component if post has no user

2022-06-06 12:01 UTC, Denchepornyuk approved these changes

2024-03-19 15:03 UTC, closed without merging